# Generated by Django 3.0 on 2021-02-22 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='notes',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='experience',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL),
        ),
    ]
